from abc import ABC, abstractmethod

import numpy as np
from attrs import field, define, validators
from numpy.typing import ArrayLike

from h2integrate.core.utilities import BaseConfig


# generated from np.random.SeedSequence().entropy
rng = np.random.default_rng(279299947538423226929715083173412195503)


N_TIMESTEPS = 8760


def create_failure_model(config: dict):
    """Retrieves and initializes a matching reliability model."""
    name = config["failure_model"]
    fail_config = config["failure_parameters"]
    match name:
        case "WeibullReliability":
            return WeibullReliability.from_dict(fail_config)
        case "FixedIntervalReliability":
            return FixedIntervalReliability.from_dict(fail_config)
        case _:
            raise NotImplementedError(f"{name} is not a valid model name")


def create_maintenance_model(config: dict):
    """Retrieves and initializes a matching reliability model."""
    name = config["maintenance_model"]
    maintenance_config = config["maintenance_parameters"]
    match name:
        case "WeibullReliability":
            return WeibullReliability.from_dict(maintenance_config)
        case "FixedIntervalReliability":
            return FixedIntervalReliability.from_dict(maintenance_config)
        case _:
            raise NotImplementedError(f"{name} is not a valid model name")


def generate_downtime_model(config: dict | int):
    if not isinstance(config, dict):
        return FixedDowntime(hours=config)
    name = config["model"]
    parameters = {k: v for k, v in config.items() if k != "model"}
    match name:
        case "LogNormalDowntime":
            return LogNormalDowntime.from_dict(parameters)
        case "FixedDowntime":
            return FixedDowntime.from_dict(parameters)
        case _:
            raise NotImplementedError(f"{name} is not a valid model name")


@define(kw_only=True)
class BaseDowntime(ABC, BaseConfig):
    @abstractmethod
    def sample_downtime(self) -> np.ndarray: ...


@define(kw_only=True)
class BaseReliability(BaseConfig):
    """Base reliability class responsible for common definitions and functionality.

    Args:
        burn_in (float): Number of years into the simulation to use as the starting point of the
            the simulation's availability record. Defaults to 0.
        n_components (int): Number of identical components to sample to avoid defining an array of
            mean and sigma values when they are the same. After initialization this value changes
            to align with the number of components being simulated, regardless of identicality.
            Defaults to 1.
        downtime (dict): Configuration for a downtime model.

    Attributes:
        time_to_failures (np.ndarray): Array of the hours to the next failure for each modeled
            component. Generated by each subclass' :py:meth:`sample_events`.
        downtime_per_event (np.ndarray): Number of hours of downtime corresponding to each downtime
            event in :py:attr:`time_to_failures`.
        availability (np.ndarray): Operational ratio of each modeled component for every time step
            of the simulation.
        system_availability (np.ndarray): Minimum operational ratio of all components for every time
            time step of the simulation.
    """

    burn_in: float = field(default=0, converter=float, validator=validators.ge(0))
    n_components: int = field(default=1, validator=(validators.instance_of(int), validators.ge(1)))
    downtime: dict | BaseDowntime = field(converter=generate_downtime_model)

    time_to_failures: np.ndarray = field(init=False, validator=validators.instance_of(np.ndarray))
    downtime_per_event: np.ndarray = field(init=False, validator=validators.instance_of(np.ndarray))
    availability: np.ndarray = field(init=False, validator=validators.instance_of(np.ndarray))
    system_availability: np.ndarray = field(
        init=False, validator=validators.instance_of(np.ndarray)
    )

    def sample_events(self) -> np.ndarray:
        raise NotImplementedError("Failed to successfully subclass, please implement me.")

    def calculate_availability(self):
        """Determine the timing and duration of outages for a single year of simulation time."""
        burn_in_time = np.ceil(self.burn_in * N_TIMESTEPS).astype(int)
        simulation_end = burn_in_time + N_TIMESTEPS

        accumulated = np.zeros((self.n_components, 1), dtype=int)
        availability = np.ones((self.n_components, simulation_end), dtype=float)

        while any(accumulated < simulation_end):
            if not self.time_to_failures.size == 0:
                self.create_downtime_events()
            event = self.time_to_failures[:, 0].reshape(-1, 1)
            self.time_to_failures = self.time_to_failures[:, 1:]
            duration = self.downtime_per_event[:, 0].reshape(-1, 1)
            self.downtime_per_event = self.downtime_per_event[:, 1:]

            if all(event + accumulated) > simulation_end:
                break

            start = accumulated + event
            end = start + duration
            for i, (s, e) in enumerate(zip(start.flatten(), end.flatten())):
                if s < simulation_end:
                    e = min(simulation_end, e)
                    availability[i, s:e] = 0
            accumulated = end

        self.availability = availability[:, burn_in_time:simulation_end]
        self.system_availability = np.min(self.availability, axis=0)


def float_array_converter(val: int | float | ArrayLike):
    return np.array(val).astype(float).reshape(-1, 1)


def int_array_converter(val: int | float | ArrayLike):
    return np.array(val).astype(int).reshape(-1, 1)


@define(kw_only=True)
class FixedDowntime(BaseDowntime):
    """Basic log-normal downtime model for generating the length of downtime for a given event.

    Args:
        hours (int | array-like): Length of downtime per event, in hours. Must be at least 1 hour.
        n_components (int): Number of identical components to sample to avoid defining an array of
            :py:attr:`hours` values when they are the same. Defaults to 1.
    """

    hours: int | ArrayLike = field(
        converter=int_array_converter,
        validator=validators.instance_of(np.ndarray),
    )
    n_components: int = field(default=1, validator=(validators.instance_of(int), validators.ge(1)))

    @hours.validator
    def hours_validator(self, attribute, value):
        """Validates that all values of :py:attr:`hours` are greater than or equal to 1."""
        if not np.all(value > 1):
            raise ValueError("All values passed to 'hours' must be greater than or equal to 1.")

    def __attrs_post_init__(self):
        if self.hours.size == 1 and self.n_components > 1:
            shape = (self.n_components, 1)
            self.hours = np.broadcast_to(self.hours, shape)
        self.n_components = self.hours.size

    def sample_downtime(self):
        """Return an array of 100 :py:attr:`hours`."""
        return np.ones((1, 100), dtype=int) * self.hours


@define(kw_only=True)
class LogNormalDowntime(BaseDowntime):
    """Basic log-normal downtime model for generating the length of downtime for a given event.

    Args:
        mean (float | array-like): Average length of downtime per event, in hours.
        sigma (float | array-like): Standard deviation of the distribution(s), in hours.
    """

    mean: float = field(
        converter=float_array_converter,
        validator=(validators.instance_of(np.ndarray)),
    )
    sigma: float = field(
        converter=float_array_converter,
        validator=(validators.instance_of(np.ndarray)),
    )
    n_components: int = field(default=1, validator=(validators.instance_of(int), validators.ge(1)))

    @mean.validator
    @sigma.validator
    def validate_ge_zero(self, attribute, value):
        """Validates the :py:attr:`sigma` and :py:attr:`mean` values are at least 0."""
        if any(value < 0):
            raise ValueError(f"'{attribute.name}' must have all values of at least 0.")

    @sigma.validator
    def validate_shape(self, attribute, value):
        """Validates that :py:attr:`mean` and :py:attr:`sigma` are the same size."""
        if self.mean.shape != value.shape:
            msg = (
                "Inputs to 'mean' and 'sigma' must be the same length. Received"
                f" 'mean': {self.mean.size}, 'sigma': {value.size}"
            )
            raise ValueError(msg)

    def __attrs_post_init__(self):
        if self.mean.size == 1 and self.n_components > 1:
            shape = (self.n_components, 1)
            self.mean = np.broadcast_to(self.mean, shape)
            self.sigma = np.broadcast_to(self.sigma, shape)
        self.n_components = self.mean.size

    def sample_downtime(self) -> np.ndarray:
        """Return an array of 100 samples of each lognormal distribution."""
        return np.ceil(rng.lognormal(self.mean, self.sigma, size=(self.mean.shape[0], 100))).astype(
            int
        )


@define(kw_only=True)
class WeibullReliability(BaseReliability):
    r"""Basic reliability model for operating/not operating statuses.

    Assumes a full operational shutdown with zero ramping of production for an hourly, 1 year
    simulation.

    Args:
        scale (float): Also referred to as :math:`\lambda` or :math:`\alpha`. Determines
            the scale of distribution, and is equivalent to the mean time
            between failure in years (MTBF), or 1 / annual failure rate.
        shape (float): Also referred to as ``k`` or :math:`\beta`. A value less than 1
            corresponds to a decreasing hazard rate over time (break-in period failures);
            a value greater than 1 corresponds to an increasing hazard rate over time (
            aging/wear-out failures); and a value of 1 corresponds to a constant hazard
            rate over time (exponential distribution).
        downtime (float): Average amount of downtime per failure.

    Attributes:
        rng (np.random._generator.Generator): NumPy random generator object.

    TODO:
        - how to pass n_timesteps through from plant?
        - burn-in
    """

    scale: float = field(
        converter=float_array_converter,
        validator=validators.instance_of(np.ndarray),
    )
    shape: float = field(
        converter=float_array_converter,
        validator=validators.instance_of(np.ndarray),
    )

    def __attrs_post_init__(self):
        if self.scale.size == 1 and self.n_components > 1:
            shape = (self.n_components, 1)
            self.scale = np.broadcast_to(self.scale, shape)
            self.shape = np.broadcast_to(self.shape, shape)
        self.n_components = self.scale.size

        self.create_downtime_events()
        self.calculate_availability()

    def sample_events(self):
        """Samples 100 events for each simulated component, rounding up to the nearest timestep."""
        return np.ceil(
            rng.weibull(self.shape, size=(self.shape.size, 100)) * self.scale * N_TIMESTEPS
        ).astype(int)

    def create_downtime_events(self):
        """Creates a ``time_to_failure`` and ``downtime_per_event``."""
        self.time_to_failures = self.sample_events()
        self.downtime_per_event = self.downtime.sample_downtime()


@define(kw_only=True)
class FixedIntervalReliability(BaseReliability):
    """Basic fixed interval downtime reliability model.

    Args:
        frequency (int | float | array-like): The annual frequency of events, e.g., 4 is equivalent
            to a quarterly downtime event and 0.25 is equivalent to an every 4 years downtime event.
            For all events the timing of the first event will be sampled within the first year or
            interval period to offset events from being based on January 1st in an 8760.
        downtime (int | float | dict): Either fixed length of each downtime, in hours, or a
            configuration dictionary for a downtime length model.
    """

    frequency: float = field(
        converter=float_array_converter,
        validator=validators.instance_of(np.ndarray),
    )

    def __attrs_post_init__(self):
        if self.frequency.size == 1 and self.n_components > 1:
            shape = (self.n_components, 1)
            self.frequency = np.broadcast_to(self.frequency, shape)
        self.n_components = self.frequency.size

        self.create_downtime_events()
        self.calculate_availability()

    @frequency.validator
    def validate_frequency(self, attribute, value):
        """Validates all passed values to :py:attr:`frequency` are greater than 0."""
        if any(value <= 0):
            raise ValueError("All values of 'frequency' must be greater than 0.")

    def sample_events(self):
        """Creates the time to next failure array for each event's modality with the first event
        occurring randomly either in the first year or first failure interval, whichever
        comes first.

        Returns:
            time_to_failures (np.ndarray): An array of the next 100 events' time to next failure.
        """
        interval = np.ceil(8760 / (1 / self.frequency)).astype(int)
        first_occurrence = rng.integers(0, np.where(interval > 8760, 8760, interval))
        time_to_failures = np.hstack(
            (first_occurrence, np.broadcast_to(interval, (interval.size, 99)))
        )
        return time_to_failures

    def create_downtime_events(self):
        """Creates a ``time_to_failure`` and ``downtime_per_event``."""
        self.time_to_failures = self.sample_events()
        self.downtime_per_event = self.downtime.sample_downtime()
