from copy import deepcopy

import numpy as np
from attrs import field, define
from attrs.validators import in_

import h2integrate.converters.combustion_machines.NGCT_thermo_model as NGCT
from h2integrate.core.utilities import BaseConfig, merge_shared_inputs
from h2integrate.core.validators import gt_zero, gte_zero
from h2integrate.core.model_baseclasses import PerformanceModelBaseClass


@define(kw_only=True)
class SimpleCycleTurbinePerformanceConfig(BaseConfig):
    """
    Configuration class for a simple Brayton-cycle turbine performance model.

    This configuration class handles the parameters for generic combustion
    turbines assuming simple Brayton-cycle thermodynamics models with isentropic
    efficiency corrections for compressor and turbine work, and compensation
    for ambient conditions.

    Attributes:
        flowrate_max_fluid_cubic_m_per_s (float): maximum volumetric flowrate of
            working fluid through the turbine in m^3/s.

        system_capacity_mw (float): rated system capacity in MW.

        generator_efficiency (float): efficiency of the generator connected to the turbine.

        generator_nameplate_power (float):
            total power output (after power factor & MVA capacity) allowed by the generator.

        pressure_ratio (float): pressure ratio generated by the compressor.

        firing_temp_C (float): firing temperature of the turbine in degrees Celsius.

        isentropic_efficiency_compressor (float): isentropic efficiency of the compressor.

        isentropic_efficiency_turbine (float): isentropic efficiency of the turbine.
    """

    flowrate_max_fluid_cubic_m_per_s: float = field(validator=gt_zero)
    system_capacity_mw: float = field(validator=gte_zero)
    generator_efficiency: float = field(validator=gt_zero)
    generator_nameplate_power_mw: float = field(validator=gt_zero)
    pressure_ratio: float = field(validator=gt_zero)
    firing_temp_C: float = field(validator=gt_zero)
    isentropic_efficiency_compressor: float = field(validator=gt_zero)
    isentropic_efficiency_turbine: float = field(validator=gt_zero)
    fuel_source: str = field(
        validator=in_(
            [
                "natural_gas",
            ]
        )
    )  # TODO: add more here...


class SimpleCycleTurbinePerformanceModel(PerformanceModelBaseClass):
    """
    Performance model for simple Brayton-cycle turbines.

    This model will compute the electricity output from a simple Brayton-cycle
    combustion turbine directly connected at the shaft to a generator, using
    real-time or provided ambient conditions and a working fluid and fuel of
    choice.

    Inputs:
        ???

    Outputs:
        ???
    """

    _time_step_bounds = (
        300,  # 5 min. run
        3600,  # 1 hr. run
    )  # (min, max) time step lengths (in seconds) compatible with this model
    _control_classifier = "dispatchable"

    def initialize(self):
        super().initialize()
        self.commodity = "electricity"
        self.commodity_rate_units = "MW"
        self.commodity_amount_units = "MW*h"

    def setup(self):
        super().setup()

        self.config = SimpleCycleTurbinePerformanceConfig.from_dict(
            merge_shared_inputs(self.options["tech_config"]["model_inputs"], "performance"),
            additional_cls_name=self.__class__.__name__,
        )

        # add solar resource data to access ambient conditions consistently
        self.add_discrete_input(
            "solar_resource_data",
            val={},
            desc="Solar resource data dictionary",
        )

        # add natural gas consumed output
        self.add_output(
            f"{self.config.fuel_source}_consumed",
            val=0.0,
            shape=self.n_timesteps,
            units="kJ/s",
            desc="natural gas consumed by the plant",
        )

        # add system max rated capacity as an input w/ config value as default
        self.add_input(
            "system_capacity",
            val=self.config.system_capacity_mw,
            units="MW",
            desc="rated combustion turbine capacity in MW",
        )

        if self.config.generator_nameplate_power_mw:
            self.add_input(
                "generator_nameplate_power",
                val=self.config.generator_nameplate_power_mw,
                units="MW",
                desc="generator nameplate capacity in MW",
            )

        # default the electricity command value input as the rated capacity
        self.add_input(
            f"{self.commodity}_command_value",
            val=self.config.system_capacity_mw,
            shape=self.n_timesteps,
            units=self.commodity_rate_units,
            desc="electricity command value for natural gas plant",
        )

        # add max volumetric flowrate as an input w/ config value as default
        self.add_input(
            "flowrate_max_fluid",
            val=self.config.flowrate_max_fluid_cubic_m_per_s,
            units="m**3/s",
            desc="maximum volumetric flowrate of working fluid through the turbine",
        )

        # add fuel input, default to 0 --> set using feedstock component
        self.add_input(
            f"{self.config.fuel_source}_in",
            val=0.0,
            shape=self.n_timesteps,
            units="kJ/s",
            desc="fuel input energy to the turbine/plant",
        )

        self.add_output(
            f"unmet_{self.commodity}_demand",
            val=0.0,
            shape=self.n_timesteps,
            units=self.commodity_rate_units,
            desc="unmet demand for electricity from the turbine/plant",
        )

        self.add_output(
            f"{self.commodity}_headroom",
            val=0.0,
            shape=self.n_timesteps,
            units="MW",
            desc="accessible reserve headroom for the system",
        )

        self.ngct = NGCT.NGCT(
            ratio_P=self.config.pressure_ratio,
            Trel_firing=self.config.firing_temp_C,
            isentropic_efficiency_compressor=self.config.isentropic_efficiency_compressor,
            isentropic_efficiency_turbine=self.config.isentropic_efficiency_turbine,
            Q_fluid_max=1.0,  # (explicitly) unit-mass analysis
        )

        # try to run NGCT cycle here expensively, and all compute variations
        # should be derivable w/o major new computation after that
        P_ambient = 101325.0  # Pa
        T_ambient = 15.0  # °C
        self.working_fluid = NGCT.pyfluids.Fluid(NGCT.pyfluids.FluidsList.Air)
        wx_data = [(T_ambient, P_ambient)]
        self.wx_checksums = [hash(wxd) for wxd in wx_data]
        self.ambient_fluid_list = [
            self.working_fluid.with_state(
                NGCT.pyfluids.Input.pressure(P),
                NGCT.pyfluids.Input.temperature(T),
            )
            for T, P in wx_data
        ]
        self.fundamental_cycle = self.ngct.run_turbine_model(self.ambient_fluid_list)

    def compute(self, inputs, outputs, discrete_inputs, _discrete_outputs):
        # working variables for inputs
        system_capacity_mw = float(inputs["system_capacity"][0])
        if self.config.generator_nameplate_power_mw:
            generator_nameplate_power_mw = float(inputs["generator_nameplate_power"][0])
        else:
            generator_nameplate_power_mw = np.inf
        flowrate_max_fluid_m3_per_s = float(inputs["flowrate_max_fluid"][0])
        fuel_source_heating_in_kJ_per_s = inputs[f"{self.config.fuel_source}_in"]
        generator_efficiency = self.config.generator_efficiency

        # extract from the solar resource data
        temperature_degC = discrete_inputs["solar_resource_data"]["temperature"]
        pressure_Pa = (
            discrete_inputs["solar_resource_data"]["pressure"] * 100.0
        )  # convert hPa to Pa
        wx_data = list(zip(temperature_degC.tolist(), pressure_Pa.tolist()))
        wx_checksums = [hash(wxd) for wxd in wx_data]

        # figure out if we can re-use the cache
        if not all(a == b for a, b in zip(wx_checksums, self.wx_checksums)):
            # recompute the unit-mass cycle because ambient fluid states are new
            self.wx_checksums = None  # break everything that will be recomputed
            self.ambient_fluid_list = None  # break everything that will be recomputed
            self.fundamental_cycle = None  # break everything that will be recomputed

            self.wx_checksums = wx_checksums
            self.ambient_fluid_list = [
                self.working_fluid.with_state(
                    NGCT.pyfluids.Input.pressure(P),
                    NGCT.pyfluids.Input.temperature(T),
                )
                for T, P in wx_data
            ]
            self.fundamental_cycle = self.ngct.run_turbine_model(self.ambient_fluid_list)
        # if the above didn't run, the weather checksums matched and we just use the cache

        # extract the net unit mass net work
        unit_mass_net_work_vec = [
            (result.process_work_unit[(3, 4)] + result.process_work_unit[(1, 2)])
            for result in self.fundamental_cycle
        ]  # kJ/kg
        unit_mass_net_heat_input_vec = [
            result.process_heat_unit[(2, 3)] for result in self.fundamental_cycle
        ]  # kJ/kg
        [result.get_efficiency() for result in self.fundamental_cycle]  # -

        # compute the rating/flowrate/input heat limited flowrate
        mass_flowrates = [
            NGCT.NGCT.get_mass_flowrate(
                fluid_ambient=fluid_ambient,
                Q_fluid_max=flowrate_max_fluid_m3_per_s,
                wdot_turbine=result.process_work_unit[(3, 4)],
                wdot_compressor=result.process_work_unit[(1, 2)],
                qdot_HX_combustor=result.process_heat_unit[(2, 3)],
                power_rated=generator_nameplate_power_mw * 1000.0,  # expects kW, convert from MW
                heatrate_fuel_capacity=fuel_source_in,
            )
            for fluid_ambient, result, fuel_source_in in zip(
                self.ambient_fluid_list,
                self.fundamental_cycle,
                fuel_source_heating_in_kJ_per_s.squeeze().tolist(),
            )
        ]
        mass_flowrates_max = deepcopy(mass_flowrates)

        # do simplified throttling of the mass flowrates if we are below the command value
        electricity_command_value = inputs["electricity_command_value"]
        mass_flowrates = np.minimum(
            mass_flowrates_max,
            1000.0 * electricity_command_value / generator_efficiency / unit_mass_net_work_vec,
        )

        # get the net work and heat input related to the mass flowrates
        net_work_vec = np.array(
            [m * w / 1000.0 for m, w in zip(mass_flowrates, unit_mass_net_work_vec)]
        )  # MW
        net_heat_input_vec = [
            m * q for m, q in zip(mass_flowrates, unit_mass_net_heat_input_vec)
        ]  # kJ/s

        # get the maximum net work the system could do given current conditions
        max_net_work_vec = np.array(
            [m * w / 1000.0 for m, w in zip(mass_flowrates_max, unit_mass_net_work_vec)]
        )  # MW

        # compute the electricity out and package work and heat outputs
        electricity_out = generator_efficiency * net_work_vec  # MW
        outputs["electricity_out"] = electricity_out
        outputs[f"{self.config.fuel_source}_consumed"] = net_heat_input_vec

        outputs["rated_electricity_production"] = (
            system_capacity_mw  # QUESTION!!!!! WHAT IS RATED???
        )

        max_production = inputs["system_capacity"] * len(electricity_out) * self.dt / 3600.0

        outputs["total_electricity_produced"] = np.sum(electricity_out) * self.dt / 3600.0
        outputs["capacity_factor"] = outputs["total_electricity_produced"].sum() / max_production
        outputs["annual_electricity_produced"] = outputs["total_electricity_produced"] * (
            1 / self.fraction_of_year_simulated
        )
        outputs[f"unmet_{self.commodity}_demand"] = electricity_command_value - electricity_out

        # compute the headroom of the generator
        outputs[f"{self.commodity}_headroom"] = np.maximum(
            0.0,
            max_net_work_vec - net_work_vec,
        )
